#TCP host
host: localhost

#TCP port
port: 3333

#Whether to show the evaluation details that triggered the event
showEvaluationDetails: false

#SSL config
ssl:
  enable: false
  allowSelfSignedCert: false
  keystorePath:
  keystorePassword: 
  truststorePath:
  truststorePassword: